### ISSUE TITLE
Prepare Presentation 3 - Up-to-date report - Deadline 8 and 10 Dec)

### ISSUE THREAD

**Issue by francoiseblanc** [romancardenas/Group_E_Simulation_Lifecycle#15]
- 10 min followed by questions
- what we have achieved so far and our plan to finalize the project
- Ideally, we should have released version 1 and be able to do a demo

**Comment by staubibr** [comment]
My plan is that we go over it quickly tomorrow. Gather all comments. Then i'll fix it with Aidan over the weekend.
