### ISSUE TITLE
Application Workflow

### ISSUE THREAD

**Issue by romancardenas** [romancardenas/Group_E_Simulation_Lifecycle#3]
We should start thinking of a workflow diagram for structuring the software of the application.

**Comment by romancardenas** [comment]
Deadline: October 2020

**Comment by francoiseblanc** [comment]
Deadline for the workflow is 20 October. Is there a way to add deadline to an issue? Is it a good idea to use "Milestone" to set up deadlines?

**Comment by francoiseblanc** [comment]
Reminder for the team:

"When submitting your assignment, the name of the file must be: Group_X_D2_TOPIC.
The cover page must include names, student ids, GitHub User IDs for each group member and the link to
your GitHub Repository."

**Comment by romancardenas** [comment]
I created a milestone, I think it provides deadlines as we want. Thanks, @francoiseblanc !
