### ISSUE TITLE
Issues with run_sim and file paths for the simulator

### ISSUE THREAD

**Issue by romancardenas** [romancardenas/Group_E_Simulation_Lifecycle#32]
We must be careful with relative/absolute paths, it may lead to errors.

Can change the `run_sim` function so we don't change the current directory? In this way, we just use relative paths to files.

**Comment by francoiseblanc** [comment]
Agreed! This was my intent but I could not find a solution. I'll look into it later, but I'm open to suggestions in the meanwhile :)
